### ISSUE TITLE
Could not open database

### ISSUE THREAD

**Issue by sachin123sharma** [litehelpers/cordova-sqlite-common#1]
I have created the project using CLI and also installed the plugin using CLI. It is successfully installed. But when i tried with the sample code given here it is giving the following error. 

I have created a CordovaApp.Phone(Windows Phone 8.1)

OPEN database: my.db
db name: my.db at full path: C:\Data\Users\DefApps\APPDATA\Local\Packages\com.SVM.DR.Beta_bzbj8h50hftv4\LocalState\my.db
new transaction is waiting for open operation
OPEN database: my.db failed, aborting any pending transactions

**Comment by brodybits** [comment]
Looks like an old question, closing.
